[Journal]
Storage=auto
#Compress=yes
#Seal=yes
#SplitMode=uid
#SyncIntervalSec=5m
#RateLimitIntervalSec=30s
#RateLimitBurst=10000

SystemMaxUse=32M
SystemMaxFileSize=8M
SystemMaxFiles=4
MaxRetentionSec=3day

RuntimeMaxUse=16M
RuntimeMaxFileSize=4M
RuntimeMaxFiles=4

MaxRetentionSec=1day
#MaxFileSec=1month

ForwardToSyslog=no
ForwardToKMsg=no
ForwardToConsole=no
ForwardToWall=no

#TTYPath=/dev/console
#MaxLevelStore=warning
#MaxLevelSyslog=warning
#MaxLevelKMsg=warning
#MaxLevelConsole=notice
#MaxLevelWall=crit
#LineMax=48K
#ReadKMsg=yes
#Audit=yes














